/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CChannelIdRouteImport } from './routes/c.$channelId'
import { Route as CChannelIdIndexRouteImport } from './routes/c.$channelId.index'
import { Route as CChannelIdNewRouteImport } from './routes/c.$channelId.new'
import { Route as CChannelIdAAutomationIdRouteImport } from './routes/c.$channelId.a.$automationId'
import { Route as CChannelIdTThreadIdRouteImport } from './routes/c.$channelId.t.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CChannelIdRoute = CChannelIdRouteImport.update({
  id: '/c/$channelId',
  path: '/c/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const CChannelIdIndexRoute = CChannelIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CChannelIdRoute,
} as any)
const CChannelIdNewRoute = CChannelIdNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CChannelIdRoute,
} as any)
const CChannelIdAAutomationIdRoute = CChannelIdAAutomationIdRouteImport.update({
  id: '/a/$automationId',
  path: '/a/$automationId',
  getParentRoute: () => CChannelIdRoute,
} as any)
const CChannelIdTThreadIdRoute = CChannelIdTThreadIdRouteImport.update({
  id: '/t/$threadId',
  path: '/t/$threadId',
  getParentRoute: () => CChannelIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/settings': typeof SettingsRoute
  '/c/$channelId': typeof CChannelIdRouteWithChildren
  '/c/$channelId/new': typeof CChannelIdNewRoute
  '/c/$channelId/': typeof CChannelIdIndexRoute
  '/c/$channelId/a/$automationId': typeof CChannelIdAAutomationIdRoute
  '/c/$channelId/t/$threadId': typeof CChannelIdTThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/settings': typeof SettingsRoute
  '/c/$channelId/new': typeof CChannelIdNewRoute
  '/c/$channelId': typeof CChannelIdIndexRoute
  '/c/$channelId/a/$automationId': typeof CChannelIdAAutomationIdRoute
  '/c/$channelId/t/$threadId': typeof CChannelIdTThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/settings': typeof SettingsRoute
  '/c/$channelId': typeof CChannelIdRouteWithChildren
  '/c/$channelId/new': typeof CChannelIdNewRoute
  '/c/$channelId/': typeof CChannelIdIndexRoute
  '/c/$channelId/a/$automationId': typeof CChannelIdAAutomationIdRoute
  '/c/$channelId/t/$threadId': typeof CChannelIdTThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/settings'
    | '/c/$channelId'
    | '/c/$channelId/new'
    | '/c/$channelId/'
    | '/c/$channelId/a/$automationId'
    | '/c/$channelId/t/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/settings'
    | '/c/$channelId/new'
    | '/c/$channelId'
    | '/c/$channelId/a/$automationId'
    | '/c/$channelId/t/$threadId'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/settings'
    | '/c/$channelId'
    | '/c/$channelId/new'
    | '/c/$channelId/'
    | '/c/$channelId/a/$automationId'
    | '/c/$channelId/t/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  SettingsRoute: typeof SettingsRoute
  CChannelIdRoute: typeof CChannelIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$channelId': {
      id: '/c/$channelId'
      path: '/c/$channelId'
      fullPath: '/c/$channelId'
      preLoaderRoute: typeof CChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$channelId/': {
      id: '/c/$channelId/'
      path: '/'
      fullPath: '/c/$channelId/'
      preLoaderRoute: typeof CChannelIdIndexRouteImport
      parentRoute: typeof CChannelIdRoute
    }
    '/c/$channelId/new': {
      id: '/c/$channelId/new'
      path: '/new'
      fullPath: '/c/$channelId/new'
      preLoaderRoute: typeof CChannelIdNewRouteImport
      parentRoute: typeof CChannelIdRoute
    }
    '/c/$channelId/a/$automationId': {
      id: '/c/$channelId/a/$automationId'
      path: '/a/$automationId'
      fullPath: '/c/$channelId/a/$automationId'
      preLoaderRoute: typeof CChannelIdAAutomationIdRouteImport
      parentRoute: typeof CChannelIdRoute
    }
    '/c/$channelId/t/$threadId': {
      id: '/c/$channelId/t/$threadId'
      path: '/t/$threadId'
      fullPath: '/c/$channelId/t/$threadId'
      preLoaderRoute: typeof CChannelIdTThreadIdRouteImport
      parentRoute: typeof CChannelIdRoute
    }
  }
}

interface CChannelIdRouteChildren {
  CChannelIdNewRoute: typeof CChannelIdNewRoute
  CChannelIdIndexRoute: typeof CChannelIdIndexRoute
  CChannelIdAAutomationIdRoute: typeof CChannelIdAAutomationIdRoute
  CChannelIdTThreadIdRoute: typeof CChannelIdTThreadIdRoute
}

const CChannelIdRouteChildren: CChannelIdRouteChildren = {
  CChannelIdNewRoute: CChannelIdNewRoute,
  CChannelIdIndexRoute: CChannelIdIndexRoute,
  CChannelIdAAutomationIdRoute: CChannelIdAAutomationIdRoute,
  CChannelIdTThreadIdRoute: CChannelIdTThreadIdRoute,
}

const CChannelIdRouteWithChildren = CChannelIdRoute._addFileChildren(
  CChannelIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  SettingsRoute: SettingsRoute,
  CChannelIdRoute: CChannelIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
